FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY security/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY security /app/security

EXPOSE 9000
CMD ["uvicorn", "security.main:app", "--host", "0.0.0.0", "--port", "9000"]
